// lib/firebase_options.dart
// Minimal placeholder for Firebase options. Replace this file by running
// `flutterfire configure` which will generate a platform-aware
// `DefaultFirebaseOptions` implementation for your Firebase project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Minimal placeholder DefaultFirebaseOptions used by the app.
///
/// IMPORTANT: Replace this with the file generated by the FlutterFire CLI.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Return a simple placeholder. Real app must replace with generated values.
    return const FirebaseOptions(
      apiKey: 'REPLACE_ME',
      appId: 'REPLACE_ME',
      messagingSenderId: 'REPLACE_ME',
      projectId: 'REPLACE_ME',
    );
  }
}

