// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGSMOc77DwzU4F3GVH52eNj4RjFzvcmPE',
    appId: '1:119871439470:web:f49ba7397405e554685c7f',
    messagingSenderId: '119871439470',
    projectId: 'activity-tracker-28ccf',
    authDomain: 'activity-tracker-28ccf.firebaseapp.com',
    storageBucket: 'activity-tracker-28ccf.firebasestorage.app',
    measurementId: 'G-222HBT2J02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ9S6_CI0V3p52Wc3EM7pNIIeQU8CpP4E',
    appId: '1:119871439470:android:c14380d5c9a73908685c7f',
    messagingSenderId: '119871439470',
    projectId: 'activity-tracker-28ccf',
    storageBucket: 'activity-tracker-28ccf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASsYQgomA8OwkE1f4fTEyDSTTbfRZUCxY',
    appId: '1:119871439470:ios:a9ebb2f1489054a8685c7f',
    messagingSenderId: '119871439470',
    projectId: 'activity-tracker-28ccf',
    storageBucket: 'activity-tracker-28ccf.firebasestorage.app',
    iosBundleId: 'com.example.tamilQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASsYQgomA8OwkE1f4fTEyDSTTbfRZUCxY',
    appId: '1:119871439470:ios:a9ebb2f1489054a8685c7f',
    messagingSenderId: '119871439470',
    projectId: 'activity-tracker-28ccf',
    storageBucket: 'activity-tracker-28ccf.firebasestorage.app',
    iosBundleId: 'com.example.tamilQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpb_bDjZ0J3O3medEhfISZVcCWFjaYzRg',
    appId: '1:119871439470:web:fc699bb7530e5943685c7f',
    messagingSenderId: '119871439470',
    projectId: 'activity-tracker-28ccf',
    authDomain: 'activity-tracker-28ccf.firebaseapp.com',
    storageBucket: 'activity-tracker-28ccf.firebasestorage.app',
    measurementId: 'G-1062147LD4',
  );
}
